# Generated by Django 2.2.9 on 2020-03-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="musicupload",
            name="splash_featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="musicupload",
            name="suspicious",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="song", name="online", field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="song",
            name="processing",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="song", name="visible", field=models.BooleanField(default=False),
        ),
    ]
