# Generated by Django 2.2.9 on 2021-02-12 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0003_auto_20200415_1109"),
    ]

    operations = [
        migrations.AddField(
            model_name="listen", name="free", field=models.BooleanField(default=False),
        ),
    ]
