# Generated by Django 2.2.9 on 2021-08-31 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0004_listen_free"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="listen", options={"get_latest_by": "datetime"},
        ),
        migrations.AlterModelOptions(
            name="musicupload", options={"get_latest_by": "upload_date"},
        ),
        migrations.AlterModelOptions(
            name="photo", options={"get_latest_by": "upload_date"},
        ),
        migrations.AlterModelOptions(
            name="video", options={"get_latest_by": "upload_date"},
        ),
    ]
