# Generated by Django 2.2.9 on 2020-03-02 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=60, null=False)),
                ("starts", models.DateTimeField()),
                ("ends", models.DateTimeField(blank=True, null=True)),
                ("location_text", models.CharField(blank=True, max_length=300)),
                ("description", models.TextField()),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("ticket_url", models.CharField(blank=True, max_length=300)),
                (
                    "artists",
                    models.ManyToManyField(
                        blank=True, related_name="shows", to="accounts.Profile"
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.Location",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="accounts.Profile",
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.Venue",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FanEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fanned_date", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "fanned_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fan_events",
                        to="events.Event",
                    ),
                ),
                (
                    "fanner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fan_events",
                        to="accounts.Profile",
                    ),
                ),
            ],
        ),
    ]
