# Generated by Django 2.2.9 on 2021-08-31 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event", options={"get_latest_by": "created"},
        ),
        migrations.AlterModelOptions(
            name="fanevent", options={"get_latest_by": "fanned_date"},
        ),
    ]
