# Generated by Django 2.2.9 on 2020-03-02 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Receipt",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_cashed", models.DateTimeField(auto_now=True)),
                ("error_message", models.CharField(max_length=40)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("unknown", "Status is unknown."),
                            ("pending", "Pending transmission to bank."),
                            ("error", "There was an error processing this reciept."),
                            ("batched", "Sent to the bank successfully!"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipts",
                        to="accounts.Profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CreditCard",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last4", models.CharField(max_length=4)),
                ("cardType", models.CharField(max_length=20)),
                ("stripe_id", models.CharField(max_length=20)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_cards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BankInfo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("routing_number", models.CharField(max_length=9)),
                ("account_number", models.CharField(max_length=17)),
                ("account_holder_name", models.CharField(max_length=22)),
                ("verified", models.BooleanField()),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank",
                        to="accounts.Profile",
                    ),
                ),
            ],
        ),
    ]
