# Generated by Django 2.2.9 on 2020-03-16 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment_processing", "0002_auto_20200306_0933"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receipt",
            name="error_message",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
