# Generated by Django 2.2.9 on 2021-08-31 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0002_auto_20200302_1419"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message", options={"get_latest_by": "timestamp"},
        ),
    ]
