version: '3.6'

volumes:
    redisdata:

networks:
    cluster:

secrets:
    .env:
        file: ../../hts/.env.dev

services:
    hts:
        tty: true # color log output
        # image: hearo/hts
        image: $IMAGE_HTS
        volumes:
            - ../../hts:/app:cached
        networks:
            - cluster
        ports:
            - '8090:8080'
        secrets:
            - .env
        environment:
            - GIT_RELEASE=$P_GIT_RELEASE
            - DEBUG=0
            # - NODEADDRESS=testnet.hedera.com
            # - NODEPORT=50003
            # - H_HTS_API_URL=http://hts:8090
            # - HEDERA_ENVIRONMENT=TESTNET
            # - MAINNET_NODE_3="35.237.200.180:50211"
            # - MAINNET_NODE_4="35.186.191.247:50211"
            # - MAINNET_NODE_7="35.203.82.240:50211"
            # - MAINNET_NODE_8="35.236.5.219:50211"
            # - MAINNET_NODE_9="35.197.192.225:50211"
            # - MAINNET_NODE_10="35.242.233.154:50211"
            # - MAINNET_NODE_11="35.240.118.96:50211"
            # - MAINNET_NODE_12="35.204.86.32:50211"
        command: mvn spring-boot:run
        # command: /bin/sh -c "while true; do sleep 100; done"
        logging:
            # limit logs retained on host to 25MB
            driver: "json-file"
            options:
                max-size: "500k"
                max-file: "50"
