# Generated by Django 2.2.9 on 2020-03-03 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_auto_20200302_1229"),
    ]

    operations = [
        migrations.AlterField(
            model_name="musician", name="dj", field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="musician",
            name="join_band",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="musician",
            name="teacher",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="musician",
            name="write_music",
            field=models.BooleanField(default=False),
        ),
    ]
