# Generated by Django 2.2.9 on 2020-03-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_auto_20200306_0933"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="passed_join_social",
            field=models.BooleanField(default=False),
        ),
    ]
