# Generated by Django 2.2.9 on 2020-03-25 17:33

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0005_person_passed_join_social"),
    ]

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("openpgp_key", models.TextField(verbose_name="OpenPGP Key")),
                (
                    "hedera_account_id",
                    models.CharField(max_length=20, verbose_name="Hedera Account ID"),
                ),
                (
                    "hedera_private_key",
                    models.TextField(verbose_name="Hedera Private Key"),
                ),
                (
                    "hedera_public_key",
                    models.CharField(max_length=100, verbose_name="Hedera Public Key"),
                ),
                (
                    "solidity_address",
                    models.CharField(max_length=100, verbose_name="Solidity Address"),
                ),
                ("token_balance", models.BigIntegerField(default=0)),
                (
                    "token_balance_last_update",
                    models.DateTimeField(default=None, null=True),
                ),
                ("allowance", models.BigIntegerField(default=0)),
                (
                    "allowance_last_update",
                    models.DateTimeField(default=None, null=True),
                ),
                ("contract_id", models.CharField(max_length=20, null=True)),
                ("date_added", models.DateField(auto_now_add=True, null=True)),
                ("received_starter_tokens", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WalletRecovery",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_added", models.DateField(auto_now_add=True, null=True)),
                ("encrypted_key", models.TextField(verbose_name="Encrypted key")),
                (
                    "recovery_key_hashes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100), size=None
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet_recovery",
                        to="accounts.Wallet",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TokenTransfer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.BigIntegerField(default=0)),
                ("treasury", models.BooleanField(default=False)),
                ("success", models.BooleanField(default=False)),
                ("datetime", models.DateTimeField(auto_now_add=True, null=True)),
                ("datetime_success", models.DateTimeField(null=True)),
                (
                    "from_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
