# Generated by Django 2.2.9 on 2020-04-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0003_auto_20200415_1109"),
        ("accounts", "0007_auto_20200415_0613"),
    ]

    operations = [
        migrations.RemoveField(model_name="tokentransfer", name="listen",),
        migrations.AddField(
            model_name="tokentransfer",
            name="error",
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="tokentransfer",
            name="listens",
            field=models.ManyToManyField(to="media.Listen"),
        ),
    ]
