# Generated by Django 2.2.9 on 2020-05-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_profile_featured"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="date_added",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
