# Generated by Django 2.2.9 on 2020-05-24 15:07

import logging
from django.db import migrations
from django.contrib.auth.models import User


logger = logging.getLogger(__name__)


def set_date_added(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Profile = apps.get_model("accounts", "Profile")
    for profile in Profile.objects.all():
        user = profile.user
        if user:
            profile.date_added = user.date_joined
            profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_profile_date_added"),
    ]

    operations = [
        migrations.RunPython(set_date_added),
    ]
