# Generated by Django 2.2.9 on 2020-05-24 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_auto_20200524_1107"),
    ]

    operations = [
        migrations.RemoveField(model_name="profile", name="featured",),
    ]
