# Generated by Django 2.2.9 on 2020-08-14 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_remove_profile_featured"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="review", options={"get_latest_by": "review_date"},
        ),
        migrations.AlterModelOptions(
            name="statusupdate", options={"get_latest_by": "update_date"},
        ),
        migrations.AddField(
            model_name="profile",
            name="email_normalized",
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
