# Generated by Django 2.2.9 on 2021-02-07 16:08

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("media", "0003_auto_20200415_1109"),
        ("accounts", "0014_auto_20200814_0945"),
    ]

    operations = [
        migrations.CreateModel(
            name="HTSTokenTransfer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.BigIntegerField(default=0)),
                ("facilitation_fee", models.BigIntegerField(default=0)),
                ("attempted", models.PositiveIntegerField(default=0)),
                ("success", models.BooleanField(default=False)),
                ("datetime", models.DateTimeField(auto_now_add=True, null=True)),
                ("datetime_success", models.DateTimeField(null=True)),
                ("datetime_last_attempted", models.DateTimeField(null=True)),
                ("error", models.CharField(max_length=300, null=True)),
                ("data", django.contrib.postgres.fields.jsonb.JSONField()),
                (
                    "for_song",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="song_payments_received",
                        to="media.Song",
                    ),
                ),
                (
                    "from_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_payments_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "listen",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="media.Listen",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(model_name="wallet", name="allowance",),
        migrations.RemoveField(model_name="wallet", name="allowance_last_update",),
        migrations.RemoveField(model_name="wallet", name="contract_id",),
        migrations.RemoveField(model_name="wallet", name="solidity_address",),
        migrations.DeleteModel(name="TokenTransfer",),
    ]
