# Generated by Django 2.2.9 on 2021-02-15 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_auto_20210207_1108"),
    ]

    operations = [
        migrations.AlterField(
            model_name="htstokentransfer",
            name="listen",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tokentransfers",
                to="media.Listen",
            ),
        ),
    ]
