# Generated by Django 2.2.9 on 2021-02-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_auto_20210215_1043"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="account_associated_with_token",
            field=models.BooleanField(default=False),
        ),
    ]
