# Generated by Django 2.2.9 on 2021-08-31 16:12

from django.db import migrations
import logging

logger = logging.getLogger(__name__)


def fix_missing_hedera_account_ids(apps, schema_editor):
    # Fixes the HTSTokenTransfer model to set all from_hedera_account_ids
    HTSTokenTransfer = apps.get_model("accounts", "HTSTokenTransfer")
    transfers = HTSTokenTransfer.objects.exclude(from_user__wallet=None)
    logger.info("%s transfers to be updated", transfers.count())
    for transfer in transfers:
        # Retry and memo defaults are ok, we just need to fix the from_hedera_account_id
        # to have a reference to it in case the user somehow gets deleted
        transfer.from_hedera_account_id = transfer.from_user.wallet.hedera_account_id
        transfer.save()


def reverse_fix_missing_hedera_account_ids(apps, schema_editor):
    logger.warn("Reverse not possible")


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0019_auto_20210831_1210"),
    ]

    operations = [
        migrations.RunPython(
            fix_missing_hedera_account_ids, reverse_fix_missing_hedera_account_ids
        ),
    ]
