# Generated by Django 2.2.9 on 2021-08-31 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0020_auto_20210831_1212"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="band", options={"get_latest_by": "formed_date"},
        ),
        migrations.AlterModelOptions(
            name="htstokentransfer", options={"get_latest_by": "datetime"},
        ),
        migrations.AlterModelOptions(
            name="membership", options={"get_latest_by": "date_joined"},
        ),
        migrations.AlterModelOptions(
            name="person",
            options={"get_latest_by": "last_login", "verbose_name_plural": "people"},
        ),
        migrations.AlterModelOptions(
            name="profile", options={"get_latest_by": "date_added"},
        ),
        migrations.AlterModelOptions(
            name="wallet", options={"get_latest_by": "date_added"},
        ),
        migrations.AlterModelOptions(
            name="walletrecovery", options={"get_latest_by": "date_added"},
        ),
    ]
