# Generated by Django 2.2.9 on 2021-10-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0022_profile_allow_send_receive"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="suspicious",
            field=models.BooleanField(default=False),
        ),
    ]
