# Generated by Django 2.2.9 on 2021-12-07 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0023_profile_suspicious"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediadownload",
            name="media",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="download_objects",
                to="media.MusicUpload",
            ),
        ),
        migrations.AlterField(
            model_name="mediadownload",
            name="receipt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="downloads",
                to="payment_processing.Receipt",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="view",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.Profile",
            ),
        ),
    ]
